### ISSUE TITLE
Shape Plugin: shapefile '/cyclosm/data/land-high/land-high.shp' does not exist  encountered during parsing of layer 'land-high' in Layer

### ISSUE THREAD

**Issue by joshinils** [cyclosm/cyclosm-cartocss-style#593]
```
kosmtik_1  | Trace
kosmtik_1  |     at ProjectServer.raise (/usr/lib/node_modules/kosmtik/src/back/ProjectServer.js:261:13)
kosmtik_1  |     at /usr/lib/node_modules/kosmtik/src/back/ProjectServer.js:75:30
kosmtik_1  |     at /usr/lib/node_modules/kosmtik/node_modules/generic-pool/lib/generic-pool.js:283:11
kosmtik_1  |     at loaded (/usr/lib/node_modules/kosmtik/node_modules/mapnik-pool/index.js:23:37)
kosmtik_1  | Shape Plugin: shapefile '/cyclosm/data/land-high/land-high.shp' does not exist  encountered during parsing of layer 'land-high' in Layer
kosmtik_1  | [httpserver] /cyclosm/tile/20/563071/343409.png?t=1626254201504 500
```
I tried to follow the docker guide. 
i downlaoded berlin+brandenburg, renamed it to data.osm.pbf and put it into the cloned folder.
the import took some time, so i guess that worked.
kosmtik is sort of running, but i get no tiles for any location, for example http://localhost:6789/cyclosm/#20/52.61993/13.31369 is just blank, besides the ui.
looking at the developer tools of firefox in the network tab i get http-code 500 for http://localhost:6789/cyclosm/tile/20/563071/343406.png?t=1626254201504, which since it is a png should be the rendered tiles?

any help would be appreciated.

**Comment by Phyks** [comment]
We don't really provide support for Docker-based installation. This method is purely community-provided.

I guess you need to download Shapefiles, which strangely enough is commented in the Docker startup script https://github.com/cyclosm/cyclosm-cartocss-style/blob/606bbec/scripts/docker-startup.sh#L60-L61.

Fixed it in https://github.com/cyclosm/cyclosm-cartocss-style/commit/f60d347f238a0c7f8afcbd1e0fca710fee2ccc3b, I guess it should work now.

**Comment by joshinils** [comment]
well anyway, I am going to follow the non-docker way then.
it seemed to me for docker to be the easier way to go, opposed to installing everything in my system.

this is what docker-compose throws at me now:
```➜  cyclosm-cartocss-style git:(master) sudo docker-compose up kosmtik
cyclosm-cartocss-style_db_1 is up-to-date
Starting cyclosm-cartocss-style_kosmtik_1 ... done
Attaching to cyclosm-cartocss-style_kosmtik_1
kosmtik_1  | Waiting for PostgreSQL to be running
kosmtik_1  | PostgreSQL running
kosmtik_1  | python: can't open file 'scripts/get-shapefiles.py': [Errno 2] No such file or directory
kosmtik_1  | [Core] Loading config from .kosmtik-config.yml
kosmtik_1  | [Core] Loading plugin from ../plugins/base-exporters/index.js
kosmtik_1  | [Core] Loading plugin from ../plugins/hash/index.js
kosmtik_1  | [Core] Loading plugin from ../plugins/local-config/index.js
kosmtik_1  | [Core] Loading plugin from ../plugins/datasource-loader/index.js
kosmtik_1  | [Core] Loading plugin from kosmtik-overpass-layer
kosmtik_1  | [Core] Loading plugin from kosmtik-fetch-remote
kosmtik_1  | [Core] Loading plugin from kosmtik-overlay
kosmtik_1  | [Core] Loading plugin from kosmtik-open-in-josm
kosmtik_1  | [Core] Loading plugin from kosmtik-map-compare
kosmtik_1  | [Core] Loading plugin from kosmtik-osm-data-overlay
kosmtik_1  | [Core] Loading plugin from kosmtik-mapnik-reference
kosmtik_1  | [Core] Loading plugin from kosmtik-geojson-overlay
kosmtik_1  | [Core] Loading project from project.mml
kosmtik_1  | [Core] PreviewServer started, you can browse http://0.0.0.0:6789
kosmtik_1  | [Core] Creating metatiles cache dir tmp/cyclosm/meta
kosmtik_1  | [Core] Deleting previous metatiles tmp/cyclosm/meta
kosmtik_1  | [Core] Created vector cache dir tmp/cyclosm/vector
kosmtik_1  | [Local Config] Unable to load local config from /cyclosm/localconfig.js
kosmtik_1  | [Error: File not found: /cyclosm/localconfig.js]
kosmtik_1  | [Fetch Remote] Processing file http://osmdata.openstreetmap.de/download/simplified-land-polygons-complete-3857.zip
kosmtik_1  | [Fetch Remote] New file for layer land-low => /cyclosm/data/land-low/land-low
kosmtik_1  | [Fetch Remote] File already exists and not force mode /cyclosm/data/land-low/simplified-land-polygons-complete-3857.zip SKIPPING
kosmtik_1  | [Fetch Remote] Processing file http://osmdata.openstreetmap.de/download/land-polygons-split-3857.zip
kosmtik_1  | [Fetch Remote] New file for layer land-high => /cyclosm/data/land-high/land-high
kosmtik_1  | [Fetch Remote] File already exists and not force mode /cyclosm/data/land-high/land-polygons-split-3857.zip SKIPPING
kosmtik_1  | [Fetch Remote] Done.
kosmtik_1  | [Core] Generating Mapnik XML…
kosmtik_1  | [Core] Using mapnik version 3.0.20
kosmtik_1  | [Core] Loading map…
kosmtik_1  | [Core] Map ready
kosmtik_1  | [Core] Loading map…
kosmtik_1  | [Core] Map ready
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Serif Tibetan Regular' in FontSet 'fontset-0'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Emoji Regular' in FontSet 'fontset-0'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'unifont Medium' in FontSet 'fontset-0'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Serif Tibetan Bold' in FontSet 'fontset-1'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Serif Tibetan Regular' in FontSet 'fontset-1'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Emoji Regular' in FontSet 'fontset-1'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'unifont Medium' in FontSet 'fontset-1'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Serif Tibetan Regular' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Emoji Regular' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'unifont Medium' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Serif Tibetan Regular' in FontSet 'fontset-0'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Emoji Regular' in FontSet 'fontset-0'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'unifont Medium' in FontSet 'fontset-0'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Serif Tibetan Bold' in FontSet 'fontset-1'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Serif Tibetan Regular' in FontSet 'fontset-1'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Emoji Regular' in FontSet 'fontset-1'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'unifont Medium' in FontSet 'fontset-1'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Serif Tibetan Regular' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Emoji Regular' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'unifont Medium' in FontSet 'fontset-2'
kosmtik_1  | Trace
kosmtik_1  |     at ProjectServer.raise (/usr/lib/node_modules/kosmtik/src/back/ProjectServer.js:261:13)
kosmtik_1  |     at /usr/lib/node_modules/kosmtik/src/back/ProjectServer.js:75:30
kosmtik_1  |     at /usr/lib/node_modules/kosmtik/node_modules/generic-pool/lib/generic-pool.js:283:11
kosmtik_1  |     at loaded (/usr/lib/node_modules/kosmtik/node_modules/mapnik-pool/index.js:23:37)
kosmtik_1  | Shape Plugin: shapefile '/cyclosm/data/land-high/land-high.shp' does not exist  encountered during parsing of layer 'land-high' in Layer
kosmtik_1  | Shape Plugin: shapefile '/cyclosm/data/land-high/land-high.shp' does not exist  encountered during parsing of layer 'land-high' in Layer
kosmtik_1  | Trace
kosmtik_1  |     at ProjectServer.raise (/usr/lib/node_modules/kosmtik/src/back/ProjectServer.js:261:13)
kosmtik_1  |     at /usr/lib/node_modules/kosmtik/src/back/ProjectServer.js:75:30
kosmtik_1  |     at /usr/lib/node_modules/kosmtik/node_modules/generic-pool/lib/generic-pool.js:283:11
kosmtik_1  |     at loaded (/usr/lib/node_modules/kosmtik/node_modules/mapnik-pool/index.js:23:37)
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Serif Tibetan Regular' in FontSet 'fontset-0'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Emoji Regular' in FontSet 'fontset-0'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'unifont Medium' in FontSet 'fontset-0'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Serif Tibetan Bold' in FontSet 'fontset-1'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Serif Tibetan Regular' in FontSet 'fontset-1'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Emoji Regular' in FontSet 'fontset-1'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'unifont Medium' in FontSet 'fontset-1'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Serif Tibetan Regular' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'Noto Emoji Regular' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2021-07-14 18:35:42: warning: unable to find face-name 'unifont Medium' in FontSet 'fontset-2'
kosmtik_1  | [httpserver] /cyclosm/poll/ 200
```

**Comment by Phyks** [comment]
My bad, get-shapefiles has been removed, hence the comment in Docker startup script.

Usual way of handling the download of these files is to rely on the Kosmtik plugin https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/docs/INSTALL.md#kosmtik. I guess it is simply not installed in the Docker.

If you have a fix for this, please feel free to make a PR, I'll happily merge it.

**Comment by joshinils** [comment]
no, I don't know docker, just thought it'd be easier.
