### ISSUE TITLE
phyghtmap not working 

### ISSUE THREAD

**Issue by rkarikari** [cyclosm/cyclosm-cartocss-style#681]
Hello,
I cannot seem to get past phyghtmap errors.

Seems there's been a change in matplotlib causing this issue.

```
Traceback (most recent call last):
  File "/usr/bin/phyghtmap", line 33, in <module>
    sys.exit(load_entry_point('phyghtmap==2.23', 'console_scripts', 'phyghtmap')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/phyghtmap", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/dist-packages/phyghtmap-2.23-py3.11.egg/phyghtmap/main.py", line 17, in <module>
  File "/usr/local/lib/python3.11/dist-packages/phyghtmap-2.23-py3.11.egg/phyghtmap/hgt.py", line 18, in <module>
ImportError: cannot import name '_contour' from 'matplotlib' (/usr/lib/python3/dist-packages/matplotlib/__init__.py)
```

Is there a solution / workaround ?

**Comment by Phyks** [comment]
This is a phyghtmap issue, not a CyclOSM issue we can act upon.

See https://github.com/has2k1/plotnine/issues/619, the issue is due to a refactor in matplotlib 3.6.0. Quick workaround is to install matplotlib version below 3.6.0. Real fix is to use `contourpy` instead of `matplotlib._contour`.

You can report the bug to Panarchos user on OSM, see https://wiki.openstreetmap.org/wiki/Phyghtmap.
