### ISSUE TITLE
Postgis Plugin: ERROR:  invalid input syntax for integer: "600 m³"

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#70]
Issue in parsing numbers I guess :

```
[httpserver] /cyclosm-cartocss-style/tile/12/2087/1390.png?t=1550863968753 500
Trace
    at ProjectServer.raise (/home/olympi/node_modules/kosmtik/src/back/ProjectServer.js:261:13)
    at /home/olympi/node_modules/kosmtik/src/back/ProjectServer.js:79:34
    at /home/olympi/node_modules/kosmtik/src/back/MetatileBasedTile.js:46:45
    at FSReqWrap.oncomplete (fs.js:135:15)
Postgis Plugin: ERROR:  invalid input syntax for integer: "600 m³"
in executeQuery Full sql was: 'SELECT ST_AsBinary("way") AS geom,"access","compressed_air","feature","iata","icao" FROM (
  SELECT
    access,
    bicycle,
    covered,
    tags->'shelter' AS shelter,
    way,
    name,
    COALESCE( -- order is important here
      'aeroway_' || aeroway,
      'tourism_' || tourism,
      'amenity_' || CASE WHEN amenity != 'fuel' THEN amenity ELSE NULL END,
      'shop_' || shop,
      'emergency_' || CASE WHEN tags->'emergency' IS NOT NULL then tags->'emergency' ELSE NULL END,
      'healthcare_' || CASE WHEN tags->'healthcare' IN ('clinic', 'hospital') THEN tags->'healthcare' ELSE NULL END,
      'leisure_' || leisure,
      'man_made_' || man_made,
      'natural_' || "natural",
      'waterway_' || waterway,
      'historic_' || historic,
      'military_'|| military,
      'highway_'|| highway,
      'power_' || power,
      'tourism_' || tourism
    ) AS feature,
    (tags->'capacity')::integer AS capacity,
    tags->'compressed_air' AS compressed_air,
    tags->'drinking_water' AS drinking_water,
    tags->'location' AS location,
    tags->'memorial' AS memorial,
    tags->'castle_type' AS castle_type,
    tags->'information' AS information,
    tags->'artwork_type' as artwork_type,
    tags->'icao' as icao,
    tags->'iata' as iata,
    tags->'generator:source' as "generator:source",
    tags->'supervised' as supervised,
    tags->'bicycle_parking' as bicycle_parking,
    CASE
      WHEN "natural" IN ('peak', 'volcano', 'saddle') THEN NULL
      WHEN "waterway" IN ('waterfall') THEN
        CASE
          WHEN tags->'height' ~ '^\d{1,3}(\.\d+)?( m)?$' THEN (SUBSTRING(tags->'height', '^(\d{1,3}(\.\d+)?)( m)?$'))::NUMERIC
        ELSE NULL
        END
      WHEN tags->'capacity' IS NOT NULL THEN (tags->'capacity')::integer
      ELSE NULL
    END AS score,
    NULL AS elevation,
    CASE
      WHEN (man_made IN ('mast', 'tower', 'chimney', 'crane') AND (tags->'location' NOT IN ('roof', 'rooftop') OR (tags->'location') IS NULL)) OR waterway IN ('waterfall') THEN
        CASE
          WHEN tags->'height' ~ '^\d{1,3}(\.\d+)?( m)?$' THEN (SUBSTRING(tags->'height', '^(\d{1,3}(\.\d+)?)( m)?$'))::NUMERIC
        ELSE NULL
      END
      ELSE NULL
    END AS height,
    way_area/NULLIF(38.2185::real*38.2185::real,0) AS way_pixels
  FROM planet_osm_polygon
  WHERE aeroway IN ('helipad', 'aerodrome')
    OR tourism IN ('artwork', 'alpine_hut', 'camp_site', 'caravan_site', 'chalet', 'wilderness_hut', 'guest_house', 'apartment', 'hostel',
        'hotel', 'motel', 'information', 'museum', 'viewpoint', 'picnic_site', 'gallery')
    OR amenity IN ('bar', 'bicycle_rental', 'bicycle_parking', 'bicycle_repair_station', 'biergarten', 'cafe', 'compressed_air', 'drinking_water', 'fast_food', 'food_court', 'fountain', 'hospital', 'ice_cream', 'internet_cafe', 'pharmacy', 'police', 'post_office', 'post_box', 'pub', 'public_bath', 'restaurant', 'shelter', 'shower', 'toilets', 'water_point')
    OR tags->'compressed_air'='yes'
    OR (amenity='motorcycle_parking' AND (bicycle IS NULL OR bicycle='yes' OR bicycle='designated'))
    OR tags->'healthcare' IN ('clinic', 'hospital')
    OR shop IN ('bicycle', 'bakery', 'beverage', 'convenience', 'convenience;gas', 'greengrocer', 'supermarket', 'pastry')
    OR (shop='sports' AND (tags->'service:bicycle:retail'='yes' OR tags->'service:bicycle:repair'='yes' OR tags->'service:bicycle:rental'='yes' OR tags->'service:bicycle:pump'='yes' OR tags->'service:bicycle:diy'='yes'))
    OR leisure='picnic_table'
    OR (
      man_made IN ('mast', 'tower', 'water_tower', 'lighthouse', 'windmill', 'cross', 'obelisk', 'communications_tower', 'telescope', 'chimney', 'crane', 'storage_tank', 'silo')
      AND (tags->'location' NOT IN ('roof', 'rooftop') OR (tags->'location') IS NULL)
    )
    OR "natural" IN ('peak', 'volcano', 'saddle', 'spring', 'cave_entrance')
    OR waterway IN ('waterfall')
    OR historic IN ('memorial', 'monument', 'archaeological_site', 'wayside_cross', 'fort', 'wayside_shrine', 'castle', 'manor', 'city_gate')
    OR military IN ('bunker')
    OR tags->'emergency'='phone'
    OR highway IN ('elevator', 'traffic_signals')
    OR (highway='bus_stop' AND (tags->'shelter'='yes' OR covered='yes'))
    OR (power = 'generator' AND tags->'generator:source'='wind')
  ORDER BY
      CASE
          -- Emergency first
          WHEN tags->'healthcare' IS NOT NULL OR tags->'emergency'='phone' OR amenity IN ('hospital', 'pharmacy') THEN 0
          -- Other emergency-related amenities
          WHEN amenity IN ('bicycle_repair_station', 'compressed_air', 'drinking_water', 'police', 'toilets', 'water_point') THEN 10
          WHEN tags->'compressed_air'='yes' THEN 11
          -- Bike amenities
          WHEN shop IN ('bicycle', 'sports') OR amenity IN ('bicycle_rental') THEN 30
          -- Supermarkets
          WHEN shop='supermarket' THEN 40
          -- Convenience
          WHEN shop='convenience' OR shop='convenience;gas' THEN 50
          -- Food
          WHEN shop IS NOT NULL OR amenity IN ('bar', 'biergarten', 'cafe', 'fast_food', 'food_court', 'pub', 'restaurant') THEN 60
          -- Everything else
          ELSE NULL
      END ASC NULLS LAST,
      feature,
      score DESC NULLS LAST
) AS data WHERE "way" && ST_SetSRID('BOX3D(362005.7659585947 6388912.572188171,401141.5244406049 6428048.33067018)'::box3d, 3857)'
```

EDIT[Phyks]: Added code formatting tags.

**Comment by Florimondable** [comment]
Had in low zoom over St-Quentin (Picardie, Aisnes)

**Comment by Phyks** [comment]
Should be fixed by https://github.com/cyclosm/cyclosm-cartocss-style/commit/998510982d6bd31034fbacedc3281b7a65258616.
